# fly.toml app configuration file generated for my-expenses-bot--wkdda on 2025-05-05T13:05:21Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'my-expenses-bot--wkdda'
primary_region = 'otp'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024

[env]
  BOT_TOKEN="7322943384:AAEK5gbgn4S3kv9uhSF8H_4yhzj5EGRKKt0"
  MONGODB_URI="mongodb+srv://dbUser:WKwhmkEpaCotYbZw@cluster0.npxbpms.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"

